### ISSUE TITLE
where is the config of your code?

### ISSUE THREAD

**Issue by maominluck** [IDT-ITI/MMFusion-IML#10]
Hello author, thank you very much for your work. I would like to ask where is the config of your code, because when training example_train.sh, I encountered the problem that input and target shapes do not match. I found that the size of image size and mask are both 512, but the output result of val is different. I hope to get your reply, thank you.

**Comment by kostino** [comment]
Hi, for some datasets ( i think CASIAv2 not sure) i remember that the original version has masks that are the wrong size so i had to fix them myself. See maybe https://github.com/SunnyHaze/CASIA2.0-Corrected-Groundtruth and https://github.com/SunnyHaze/IML-Dataset-Corrections . Otherwise you need to manually find the examples where the image and mask are of different sizes and fix them
